# Generated by Django 5.0.7 on 2024-07-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicodin', '0002_category_user_age_user_avatar_user_bio_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
