# Generated by Django 5.0.7 on 2024-07-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicodin', '0004_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='prod_def.png', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='prod_def.png', null=True, upload_to='product_images/'),
        ),
    ]
