# Generated by Django 5.0.7 on 2024-07-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicodin', '0006_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vicodin.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='topic_title1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='topic_title2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='topic_title3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
