# Generated by Django 5.0.7 on 2024-07-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicodin', '0007_blog_category_blog_topic_title1_blog_topic_title2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
