# Generated by Django 5.0.7 on 2024-07-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicodin', '0008_blog_body1_blog_body2_blog_body3'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blockoute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
