# Generated by Django 5.0.7 on 2024-07-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicodin', '0010_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blockoute',
            new_name='author_description',
        ),
    ]
