# Generated by Django 5.0.7 on 2024-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicodin', '0011_rename_blockoute_blog_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
