# Generated by Django 5.0.7 on 2024-08-01 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicodin', '0015_remove_order_amount_remove_order_product_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Date must be in MM/YY format', regex='^(0[1-9]|1[0-2])\\/\\d{2}$')]),
        ),
    ]
