# Generated by Django 5.0.7 on 2024-08-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicodin', '0019_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vicodin.card'),
            preserve_default=False,
        ),
    ]
